apiVersion: v1
kind: Service
metadata:
  name: springboot-container-service
spec:
  type: NodePort
  selector:
    app: springboot-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
