apiVersion: v1
kind: Service
metadata:
  name: springboot-container
spec:
  selector:
    app: springboot-container
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
