apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-container
  namespace: my-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-container
  template:
    metadata:
      labels:
        app: springboot-container
    spec:
      containers:
      - name: springboot-container
        image: pumipat/miniproject:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://miniproject.mysql.database.azure.com:3306/miniproject?useSSL=true&requireSSL=true
        - name: SPRING_DATASOURCE_USERNAME
          value: pumipatroot@miniproject
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-mysql-secret
              key: MYSQL_PASSWORD
        resources:
          limits:
            cpu: "0.50"
            memory: 512Mi
