apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-container
  template:
    metadata:
      labels:
        app: springboot-container
    spec:
      containers:
      - name: springboot-container
        image: pumipat/miniproject:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: springboot-properties
