apiVersion: v1
kind: Service
metadata:
  name: springboot-container-service
spec:
  selector:
    app: springboot-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
