apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-container
  namespace: my-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-container
  template:
    metadata:
      labels:
        app: springboot-container
    spec:
      containers:
      - name: springboot-container
        image: pumipat/miniproject:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.my-spring-boot.svc.cluster.local:3306/miniproject
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        resources:
          limits:
            cpu: "0.50"
            memory: 512Mi