apiVersion: v1
kind: Service
metadata:
  name: springboot-container-service
  namespace: my-spring-boot
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: springboot-container
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
